# coding: utf-8
from sqlalchemy import Column, DateTime, Float, Index, String
from sqlalchemy.dialects.mysql import INTEGER, VARCHAR
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()
metadata = Base.metadata


class CnsCinfo(Base):
    __tablename__ = 'cns_cinfo'
    __table_args__ = (
        Index('IDX_CINFO_REGISTERGUID_AREACODE_STATUS_SEND', 'REGISTERGUID', 'AREACODE', 'CSTATUS', 'SENDPROPERSONGUID', 'SENDOUPERSONGUID'),
        Index('IDX_CINFO_REGISTER_AREACODE_SOURCE', 'REGISTERTIME', 'AREACODE', 'REGISTERGUID', 'RQSTSOURCE'),
        Index('cns_cinfo_rqstnumberzuhe_IDX', 'RQSTNUMBER', 'RQSTTIME')
    )

    TEMPCLIENGGUID = Column(VARCHAR(50))
    WEBCLIENGGUID = Column(String(50))
    HANDLEMANYOUGUIDLIST = Column(String(500))
    HANDLEMANYOULIST = Column(String(300))
    ISSUPPLY = Column(String(4))
    ANSWERCONTENT = Column(VARCHAR(1000))
    KEYWORDTYPE = Column(String(10))
    KEYWORDTEXT = Column(String(50))
    REVOKETIME = Column(DateTime)
    REVOKEREASONTYPE = Column(String(20))
    REVOKEREASONTEXT = Column(String(500))
    ISSENDOU = Column(String(4))
    ISDIFFICULTCASE = Column(String(4))
    REGISTERTIME = Column(DateTime)
    SENDOUTIME = Column(DateTime)
    FINISHTIME = Column(DateTime)
    FINISHTIME_BF = Column(DateTime)
    SENDOUTIME_BF = Column(DateTime)
    ABANDONTYPE = Column(String(4))
    ABANDONTEXT = Column(String(200))
    AREANAME = Column(VARCHAR(100))
    TEMPOPINION = Column(VARCHAR(400))
    SENDOUTYPE = Column(VARCHAR(8))
    CONTRACTGUID = Column(VARCHAR(50))
    ANSWERPERSON = Column(String(50))
    ISDIRECTFINISH = Column(String(50))
    SERIALNUM = Column(VARCHAR(50))
    RQSTPERSON = Column(String(500))
    RQSTSEX = Column(VARCHAR(2))
    RQSTTIME = Column(DateTime, index=True)
    RQSTNUMBER = Column(String(20))
    LINKNUMBER = Column(String(20))
    RQSTAREA = Column(VARCHAR(100))
    RQSTAREACODE = Column(VARCHAR(32))
    RQSTADDRESS = Column(VARCHAR(200))
    RQSTTYPE = Column(String(50), index=True)
    ACCORDTYPE = Column(String(500))
    ACCORDTYPECODE = Column(String(100), index=True)
    rqsttitle = Column(String(400))
    RQSTCONTENT = Column(VARCHAR(1000))
    RQSTSOURCE = Column(VARCHAR(8), index=True)
    ISIMPT = Column(VARCHAR(4))
    ISSECRET = Column(VARCHAR(4))
    RQSTEMAIL = Column(VARCHAR(200))
    ISREPLAY = Column(String(4))
    REPLAYTYPE = Column(VARCHAR(8))
    CSTATUS = Column(VARCHAR(16), index=True)
    PVIGUID = Column(VARCHAR(50), index=True)
    EVLSTYLE = Column(VARCHAR(16))
    EVLRESULT = Column(VARCHAR(16))
    ISABANDON = Column(String(4))
    HANDLEOU = Column(VARCHAR(32))
    HANDLEOUGUID = Column(VARCHAR(50))
    HANDLEXIEOULIST = Column(VARCHAR(100))
    HANDLEXIEOUGUIDLIST = Column(VARCHAR(500))
    ANSWERTIME = Column(DateTime)
    AREACODE = Column(VARCHAR(50), index=True)
    RELKNOWTIME = Column(DateTime)
    ISRELKNOW = Column(String(4))
    NOTES = Column(VARCHAR(1000))
    AGESTAGE = Column(VARCHAR(50))
    MANAGETYPE = Column(VARCHAR(50))
    REGISTERGUID = Column(String(50))
    REGISTERNAME = Column(String(50))
    CLIENGGUID = Column(String(50))
    CHECKSTATUS = Column(String(4))
    CKPERSON = Column(String(50))
    CKPERSONGUID = Column(String(50))
    DISTTIME = Column(DateTime)
    ISANSWER = Column(String(4))
    ANSWEROU = Column(String(50))
    WEBUSERGUID = Column(String(50), index=True)
    REPLAYTIME = Column(DateTime)
    AUDITFINALGUID = Column(VARCHAR(50))
    AUDITFIRSTGUID = Column(VARCHAR(50))
    HANDLEAREALIST = Column(VARCHAR(500))
    HANDLEAREAGUIDLIST = Column(VARCHAR(500))
    LNGLAT = Column(String(100))
    ABANDONTIME = Column(DateTime)
    SENDOUPERSONGUID = Column(String(50))
    ISENABLEADDTASK = Column(String(5), index=True)
    PERSONADDRESS = Column(String(150))
    OPERATEUSERNAME = Column(VARCHAR(50))
    OPERATEDATE = Column(DateTime)
    BELONGXIAQUCODE = Column(VARCHAR(50))
    ROW_ID = Column(Float)
    YEARFLAG = Column(VARCHAR(4))
    ROWGUID = Column(VARCHAR(50), primary_key=True)
    CLEARTIME = Column(INTEGER(11))
    WRONGLEVEL = Column(String(8))
    ANSWEROUGUID = Column(String(1000))
    ISNOTJXKH = Column(String(2))
    WEBRQSTTIME = Column(DateTime)
    ABANDONOU = Column(VARCHAR(50))
    EMAIL = Column(String(100))
    ISRELPROVIDE = Column(VARCHAR(50))
    ISRESULTSENDOU = Column(String(50))
    Isrecommend = Column(String(50))
    RecommendStatus = Column(String(50))
    REPLAYCONTENT = Column(VARCHAR(1000))
    SESSIONID = Column(String(100))
    TENANTGUID = Column(String(50))
    isrepeated = Column(String(4))
    samenum = Column(INTEGER(11))
    samecguid = Column(String(50), index=True)
    repeatcstatus = Column(String(4))
    transferuserguid = Column(String(500))
    customerGuid = Column(String(50))
    UNIONCGUID = Column(String(50))
    ISFIRSTCINFO = Column(String(5))
    CASETYPE = Column(String(50))
    PARENTCGUID = Column(String(50), index=True)
    BACKFLAG = Column(String(5))
    INTELIGUID = Column(String(50))
    REPLAYUSERGUID = Column(String(50))
    helpObject = Column(String(50))
    helpTypeCode = Column(String(50))
    helpTypeText = Column(String(50))
    otherHelpType = Column(String(50))
    reportObject = Column(String(50))
    reportTypeCode = Column(String(50))
    reportTypeText = Column(String(50))
    reporterName = Column(String(50))
    department = Column(String(50))
    specialFormtype = Column(String(50))
    HANDLECENTERNAME = Column(String(50))
    HANDLECENTERGUID = Column(String(50))
    industry = Column(String(50))
    startpollutiontime = Column(DateTime)
    endpollutiontime = Column(DateTime)
    MERGEAUDIT = Column(String(5))
    RQSTOBJECTTYPE = Column(String(5))
    isintelreplay = Column(String(50))
    RESULTUSERGUID = Column(String(50))
    RESULTUSERNAME = Column(String(50))
    RESULTFLAG = Column(String(5))
    OLDSTATUS = Column(String(10))
    businesstype = Column(String(50))
    issendsms = Column(String(50))
    messagecontent = Column(String(500))
    hotlinetypeguid = Column(String(50))
    hotlinetypename = Column(String(50))
    skillcodes = Column(String(50))
    reportobjectphone = Column(String(13))
    reporterPhone = Column(String(13))
    receivenumber = Column(String(13))
    FEEDTYPE = Column(String(5))
    ANSWERCLIENGGUID = Column(String(50))
    reportcliengguid = Column(String(50))
    ASSIGNNODETYPE = Column(String(50))
    showtime = Column(DateTime)
    yancsjxz = Column(DateTime)
    otherhelpobj = Column(String(50))
    otherReportType = Column(String(50))
    otherIndustry = Column(String(50))
    sqly = Column(String(50))
    sqlx = Column(String(50))
    ycsjxz = Column(String(50))
    REPEATUSERGUID = Column(String(50))
    paysavearea = Column(VARCHAR(50))
    paysaveareacode = Column(VARCHAR(50))
    SENDOUBATCH = Column(String(50))
    ANSWERPERSONGUID = Column(String(50))
    SENDPROPERSONGUID = Column(String(50))
    RECGUID = Column(String(50))
    hotrqsttypename = Column(String(50))
    hotrqsttype = Column(VARCHAR(50))
    handletimelong = Column(INTEGER(11))
    smstime = Column(DateTime, comment='通知时间')
    replaytime_bf = Column(DateTime)
    FINISHLIMITGUID = Column(VARCHAR(50))
    SENDOULIMITGUID = Column(VARCHAR(50))
    REPLAYLIMITGUID = Column(VARCHAR(50))
