# coding: utf-8
from sqlalchemy import Column, DateTime, Float, Index, String
from sqlalchemy.dialects.mysql import INTEGER, VARCHAR
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()
metadata = Base.metadata


class CnsCinfo(Base):
    __tablename__ = 'cns_cinfo'
    __table_args__ = (
        Index('cns_cinfo_registernamezuhe', 'REGISTERNAME', 'REGISTERGUID'),
    )

    TEMPCLIENGGUID = Column(VARCHAR(50))
    WEBCLIENGGUID = Column(VARCHAR(50))
    HANDLEMANYOUGUIDLIST = Column(VARCHAR(1000))
    HANDLEMANYOULIST = Column(VARCHAR(300))
    ISSUPPLY = Column(VARCHAR(4))
    ANSWERCONTENT = Column(VARCHAR(1000))
    KEYWORDTYPE = Column(VARCHAR(10))
    KEYWORDTEXT = Column(VARCHAR(100))
    REVOKETIME = Column(DateTime)
    REVOKEREASONTYPE = Column(VARCHAR(20))
    REVOKEREASONTEXT = Column(VARCHAR(500))
    ISSENDOU = Column(VARCHAR(4))
    ISDIFFICULTCASE = Column(VARCHAR(4))
    REGISTERTIME = Column(DateTime)
    SENDOUTIME = Column(DateTime, index=True)
    FINISHTIME = Column(DateTime)
    FINISHTIME_BF = Column(DateTime)
    SENDOUTIME_BF = Column(DateTime)
    ABANDONTYPE = Column(String(4))
    ABANDONTEXT = Column(String(200))
    AREANAME = Column(VARCHAR(100))
    TEMPOPINION = Column(VARCHAR(400))
    SENDOUTYPE = Column(VARCHAR(8))
    CONTRACTGUID = Column(VARCHAR(50))
    ANSWERPERSON = Column(String(50))
    ISDIRECTFINISH = Column(String(50))
    SERIALNUM = Column(VARCHAR(50))
    RQSTPERSON = Column(VARCHAR(30))
    RQSTSEX = Column(VARCHAR(2))
    RQSTTIME = Column(DateTime, index=True)
    RQSTNUMBER = Column(VARCHAR(16), index=True)
    LINKNUMBER = Column(VARCHAR(16))
    RQSTAREA = Column(VARCHAR(100))
    RQSTAREACODE = Column(VARCHAR(32))
    RQSTADDRESS = Column(VARCHAR(200))
    RQSTTYPE = Column(VARCHAR(16), index=True)
    ACCORDTYPE = Column(VARCHAR(50))
    ACCORDTYPECODE = Column(VARCHAR(16))
    RQSTTITLE = Column(VARCHAR(400))
    RQSTCONTENT = Column(VARCHAR(1000))
    RQSTSOURCE = Column(VARCHAR(8), index=True)
    ISIMPT = Column(VARCHAR(4))
    ISSECRET = Column(VARCHAR(4))
    RQSTEMAIL = Column(VARCHAR(200))
    ISREPLAY = Column(VARCHAR(4))
    REPLAYTYPE = Column(VARCHAR(8))
    CSTATUS = Column(VARCHAR(16), index=True)
    PVIGUID = Column(VARCHAR(50), index=True)
    EVLSTYLE = Column(VARCHAR(16))
    EVLRESULT = Column(VARCHAR(16))
    ISABANDON = Column(VARCHAR(4))
    HANDLEOU = Column(VARCHAR(32))
    HANDLEOUGUID = Column(VARCHAR(50))
    HANDLEXIEOULIST = Column(VARCHAR(100))
    HANDLEXIEOUGUIDLIST = Column(VARCHAR(500))
    ANSWERTIME = Column(DateTime)
    AREACODE = Column(VARCHAR(50), index=True)
    RELKNOWTIME = Column(DateTime)
    ISRELKNOW = Column(VARCHAR(4))
    NOTES = Column(VARCHAR(1000))
    AGESTAGE = Column(VARCHAR(50))
    MANAGETYPE = Column(VARCHAR(50))
    REGISTERGUID = Column(VARCHAR(50))
    REGISTERNAME = Column(VARCHAR(100))
    CLIENGGUID = Column(VARCHAR(50))
    CHECKSTATUS = Column(VARCHAR(4))
    CKPERSON = Column(VARCHAR(100))
    CKPERSONGUID = Column(VARCHAR(50))
    DISTTIME = Column(DateTime)
    ISANSWER = Column(VARCHAR(4))
    ANSWEROU = Column(VARCHAR(500))
    WEBUSERGUID = Column(VARCHAR(50))
    REPLAYTIME = Column(DateTime)
    AUDITFINALGUID = Column(VARCHAR(50))
    AUDITFIRSTGUID = Column(VARCHAR(50))
    HANDLEAREALIST = Column(VARCHAR(500))
    HANDLEAREAGUIDLIST = Column(VARCHAR(500))
    LNGLAT = Column(VARCHAR(30))
    ABANDONTIME = Column(DateTime)
    SENDOUPERSONGUID = Column(String(50))
    ISENABLEADDTASK = Column(String(5))
    PERSONADDRESS = Column(String(150))
    OPERATEUSERNAME = Column(VARCHAR(50))
    OPERATEDATE = Column(DateTime)
    BELONGXIAQUCODE = Column(VARCHAR(50))
    ROW_ID = Column(Float)
    YEARFLAG = Column(VARCHAR(4))
    ROWGUID = Column(VARCHAR(50), primary_key=True)
    CLEARTIME = Column(INTEGER(11))
    WRONGLEVEL = Column(String(8))
    ANSWEROUGUID = Column(String(1000))
    ISNOTJXKH = Column(String(2))
    WEBRQSTTIME = Column(DateTime)
    ABANDONOU = Column(VARCHAR(50))
    EMAIL = Column(String(100))
    ISRELPROVIDE = Column(VARCHAR(50))
    ISRESULTSENDOU = Column(String(50))
    Isrecommend = Column(String(50))
    RecommendStatus = Column(String(50))
    REPLAYCONTENT = Column(VARCHAR(1000))
    ISCITYLEVEL = Column(VARCHAR(8))
    SESSIONID = Column(String(100))
    TENANTGUID = Column(String(50))
    isrepeated = Column(String(4))
    samenum = Column(INTEGER(11))
    samecguid = Column(String(50))
    repeatcstatus = Column(String(4))
    transferuserguid = Column(String(500))

